### ISSUE TITLE
ParseException from Hercules.Agent.Socket

### ISSUE THREAD

**Issue by utdemir** [hercules-ci/hercules-ci-agent#237] opened 2020-08-14 11:11 UTC
**Description**

Hi. I'm trying to set up hercules-ci-agent on a NixOS machine (actually reviving a really old hercules installation, so there might be some leftover state, even though I cleaned up /var/lib/hercules). However, after the agent comes back online, I start getting log messages like:

```
Aug 14 23:08:58 home hercules-ci-agent[9132]: [2020-08-14 11:08:58][Worker.Socket][Info][home][PID 9211][ThreadId 14][exception:ParseException "not enough bytes"][message:ParseException "not enough bytes"][hercules-ci-agent-0.7.3-5tgxbNaUnDYDEQNhPuFX4E:Hercules.Agent.Socket src/Hercules/Agent/Socket.hs:106:35] Socket closed prematurely. Reconnecting.
```

And my builds are stuck in queued state.

**Platform / Version**

Here's the relevant parts of my NixOS configuration:

```
{ pkgs, ... }: {
  imports = [
    (sources.hercules-ci-agent + "/module.nix")
  ];

  services.hercules-ci-agent = {
    enable = true;
    concurrentTasks = 1;
  };
  nix.package = pkgs.nixUnstable;
}
```

Using nixpkgs rev `be42a66cd30e6bc957d919a9afbb0eb83adb6c26` and hercules-ci-agent rev `5e055d76e7553c4c5f3ac0eec59601fad25a14e6`.

**Comment by roberth** [comment] 2020-08-14 11:17
Thanks for reporting. I'm looking into it

**Comment by roberth** [comment] 2020-08-14 12:07
This seems to be a duplicate of https://github.com/hercules-ci/support/issues/30. Could you increase `concurrentTasks` from `1` to `2`.

**Comment by utdemir** [comment] 2020-08-14 23:57
Thank you for looking at it @roberth . Unfortunately increasing `concurrentTasks` did not help.

Here are the log messages after I restarted the agent after setting `concurrentTasks`:

```
Aug 15 11:54:27 home systemd[1]: Started hercules-ci-agent.service.
Aug 15 11:54:28 home hercules-ci-agent[14561]: [2020-08-14 23:54:28][][Info][home][PID 14561][ThreadId 25][agent-version:0.7.3][main:Hercules.Agent hercules-ci-agent/Hercules/Agent.hs:114:11] Agent online.
Aug 15 11:54:30 home hercules-ci-agent[14561]: [2020-08-14 23:54:30][][Info][home][PID 14561][ThreadId 35][task:8c307857-8a4e-470b-9bb4-9ef65c908fd9][agent-version:0.7.3][main:Hercules.Agent hercules-ci-agent/Hercules/Agent.hs:186:7] Starting task
Aug 15 11:54:30 home hercules-ci-agent[14561]: [2020-08-14 23:54:30][Socket][Warning][home][PID 14561][ThreadId 22][exception:CloseRequest 1000 "Closing on error"][message:CloseRequest 1000 "Closing on error"][agent-version:0.7.3][hercules-ci-agent-0.7.3-5tgxbNaUnDYDEQNhPuFX4E:Hercules.Agent.Socket src/Hercules/Agent/Socket.hs:109:35] Recovering from exception in socket handler. Reconnecting.
Aug 15 11:54:42 home hercules-ci-agent[14561]: [2020-08-14 23:54:42][][Info][home][PID 14561][ThreadId 91][task:dcd73989-f1f3-49b1-980c-784006942391][agent-version:0.7.3][main:Hercules.Agent hercules-ci-agent/Hercules/Agent.hs:186:7] Starting task
Aug 15 11:55:06 home hercules-ci-agent[14561]: [2020-08-14 23:55:06][Worker.Socket][Info][home][PID 14632][ThreadId 14][exception:ParseException "not enough bytes"][message:ParseException "not enough bytes"][hercules-ci-agent-0.7.3-5tgxbNaUnDYDEQNhPuFX4E:Hercules.Agent.Socket src/Hercules/Agent/Socket.hs:106:35] Socket closed prematurely. Reconnecting.
Aug 15 11:56:05 home hercules-ci-agent[14561]: [2020-08-14 23:56:05][][Info][home][PID 14561][ThreadId 91][task:dcd73989-f1f3-49b1-980c-784006942391][agent-version:0.7.3][main:Hercules.Agent hercules-ci-agent/Hercules/Agent.hs:168:9] Completed task successfully
Aug 15 11:56:06 home hercules-ci-agent[14561]: [2020-08-14 23:56:06][Worker.Socket][Info][home][PID 14632][ThreadId 14][exception:ParseException "not enough bytes"][message:ParseException "not enough bytes"][hercules-ci-agent-0.7.3-5tgxbNaUnDYDEQNhPuFX4E:Hercules.Agent.Socket src/Hercules/Agent/Socket.hs:106:35] Socket closed prematurely. Reconnecting.
Aug 15 11:56:23 home hercules-ci-agent[14561]: [2020-08-14 23:56:23][][Info][home][PID 14561][ThreadId 35][task:8c307857-8a4e-470b-9bb4-9ef65c908fd9][agent-version:0.7.3][main:Hercules.Agent hercules-ci-agent/Hercules/Agent.hs:168:9] Completed task successfully
Aug 15 11:56:24 home hercules-ci-agent[14561]: [2020-08-14 23:56:24][][Info][home][PID 14561][ThreadId 320][task:5f77fb2a-69d4-4e3b-91df-b902a49552de][agent-version:0.7.3][main:Hercules.Agent hercules-ci-agent/Hercules/Agent.hs:186:7] Starting task
Aug 15 11:56:24 home hercules-ci-agent[14561]: [2020-08-14 23:56:24][Socket][Warning][home][PID 14561][ThreadId 22][exception:CloseRequest 1000 "Closing on error"][message:CloseRequest 1000 "Closing on error"][agent-version:0.7.3][hercules-ci-agent-0.7.3-5tgxbNaUnDYDEQNhPuFX4E:Hercules.Agent.Socket src/Hercules/Agent/Socket.hs:109:35] Recovering from exception in socket handler. Reconnecting.
Aug 15 11:56:36 home hercules-ci-agent[14561]: [2020-08-14 23:56:36][][Info][home][PID 14561][ThreadId 353][task:1350588d-b0e3-4d92-b883-d7cba36a187e][agent-version:0.7.3][main:Hercules.Agent hercules-ci-agent/Hercules/Agent.hs:186:7] Starting task
```

**Comment by utdemir** [comment] 2020-08-15 08:14
It looks like the behaviour has changed a bit, now it's looping through these messages:

```
[root@home:~]# journalctl -f -u hercules-ci-agent
-- Logs begin at Mon 2020-03-16 19:29:01 NZDT. --
Aug 15 18:59:11 home hercules-ci-agent[14561]: [2020-08-15 06:59:11][][Info][home][PID 14561][ThreadId 57085][task:2074d96c-1b43-43d9-82a8-be320fce8eed][agent-version:0.7.3][main:Hercules.Agent hercules-ci-agent/Hercules/Agent.hs:186:7] Starting task
Aug 15 18:59:38 home hercules-ci-agent[14561]: [2020-08-15 06:59:38][Worker.Socket][Info][home][PID 27566][ThreadId 14][exception:ParseException "not enough bytes"][message:ParseException "not enough bytes"][hercules-ci-agent-0.7.3-5tgxbNaUnDYDEQNhPuFX4E:Hercules.Agent.Socket src/Hercules/Agent/Socket.hs:106:35] Socket closed prematurely. Reconnecting.
Aug 15 19:00:25 home hercules-ci-agent[14561]: [2020-08-15 07:00:25][][Info][home][PID 14561][ThreadId 57085][task:2074d96c-1b43-43d9-82a8-be320fce8eed][agent-version:0.7.3][main:Hercules.Agent hercules-ci-agent/Hercules/Agent.hs:168:9] Completed task successfully
Aug 15 19:00:27 home hercules-ci-agent[14561]: [2020-08-15 07:00:27][][Info][home][PID 14561][ThreadId 57370][task:2331892d-ae74-4f0e-aa7a-4c2ea490315e][agent-version:0.7.3][main:Hercules.Agent hercules-ci-agent/Hercules/Agent.hs:186:7] Starting task
Aug 15 19:00:35 home hercules-ci-agent[14561]: [2020-08-15 07:00:35][][Info][home][PID 14561][ThreadId 57370][task:2331892d-ae74-4f0e-aa7a-4c2ea490315e][agent-version:0.7.3][main:Hercules.Agent hercules-ci-agent/Hercules/Agent.hs:168:9] Completed task successfully
Aug 15 19:00:37 home hercules-ci-agent[14561]: [2020-08-15 07:00:37][][Info][home][PID 14561][ThreadId 57393][task:2950f3d0-17eb-4ba2-9245-7415eb128cf0][agent-version:0.7.3][main:Hercules.Agent hercules-ci-agent/Hercules/Agent.hs:186:7] Starting task
Aug 15 19:00:38 home hercules-ci-agent[14561]: [2020-08-15 07:00:38][Worker.Socket][Info][home][PID 27566][ThreadId 14][exception:ParseException "not enough bytes"][message:ParseException "not enough bytes"][hercules-ci-agent-0.7.3-5tgxbNaUnDYDEQNhPuFX4E:Hercules.Agent.Socket src/Hercules/Agent/Socket.hs:106:35] Socket closed prematurely. Reconnecting.
Aug 15 19:00:44 home hercules-ci-agent[14561]: [2020-08-15 07:00:44][][Info][home][PID 14561][ThreadId 57393][task:2950f3d0-17eb-4ba2-9245-7415eb128cf0][agent-version:0.7.3][main:Hercules.Agent hercules-ci-agent/Hercules/Agent.hs:168:9] Completed task successfully
Aug 15 19:00:45 home hercules-ci-agent[14561]: [2020-08-15 07:00:45][][Info][home][PID 14561][ThreadId 57414][task:353514c8-72c2-40b2-ada9-fbcab5c131f7][agent-version:0.7.3][main:Hercules.Agent hercules-ci-agent/Hercules/Agent.hs:186:7] Starting task
Aug 15 19:01:38 home hercules-ci-agent[14561]: [2020-08-15 07:01:38][Worker.Socket][Info][home][PID 27566][ThreadId 14][exception:ParseException "not enough bytes"][message:ParseException "not enough bytes"][hercules-ci-agent-0.7.3-5tgxbNaUnDYDEQNhPuFX4E:Hercules.Agent.Socket src/Hercules/Agent/Socket.hs:106:35] Socket closed prematurely. Reconnecting.
```

Meanwhile, the CPU is doing something heavy and some `nixbld` users are running something. But it's been quite a while like this. So it still feels to me like there is an issue.

**Comment by roberth** [comment] 2020-08-27 15:03
Generally, `ParseException "not enough bytes"` is harmless when infrequent. It seems that the websockets library reports some lost connections this way, but the agent is designed to recover correctly from a broken socket by resuming with a new one.

Agent [0.7.4](https://github.com/hercules-ci/hercules-ci-agent/releases/tag/hercules-ci-agent-0.7.4) has a fixes to preserve connections better and/or solve underlying issues. Could you update your agent and report if it happens again?

In case we need it, it's a good idea to set `services.hercules-ci-agent.extraOptions.logLevel = "DebugS";`.

**Closed** 2021-02-25 16:13 UTC
Labels: bug
