### ISSUE TITLE
NixOps deployment effect fails with: `home.mount [failed]`

### ISSUE THREAD

**Issue by nmauersberg** [hercules-ci/hercules-ci-agent#370] opened 2022-01-26 11:48 UTC
**Description**
NixOps deployment effect fails with: `home.mount [failed]`. The actual deployment worked out, but CI reports remains red due to this failure.

**To Reproduce**
The CI file is this one: https://github.com/circles-pink/circles-pink/blob/e0e116b92aa0bd4f73a9c5ffa1105fab8a61ee7a/ci.nix
Our Agent is configured and deployed from this file: https://github.com/tealverse/teal-ops/blob/ea67089b45adeb79febdd77542f42abc53ebf084/network/teal-hercules.nix

**Expected behavior**
Deploys successfully

**Logs**
https://hercules-ci.com/github/circles-pink/circles-pink/jobs/45/effects/neat-network.run/log

**Platform / Version**

- i686-linux
- x86_64-linux
- x86_64-v1-linux
- x86_64-v2-linux
- x86_64-v3-linux

Agent version :  0.8.4
Nix version: 2.4

**hercules-ci-agent --help version**
_Not sure how to figure this one out_

Any hints would be much appreciated. :)

**Comment by roberth** [comment] 2022-01-26 16:52
This seems to be a duplicate of https://github.com/NixOS/nixops/issues/1454, which might be a regression. Which revision of NixOps 2 do you use?

**Comment by roberth** [comment] 2022-01-26 17:00
You can work around problems with `nixops check` by ignoring it.

```nix
  runNixOps2 {
    effectCheckScript = "";
  }
```

Including `nixops check` by default was perhaps overly cautious.

References:

[effectCheckScript doc](https://docs.hercules-ci.com/hercules-ci-effects/reference/nix-functions/mkeffect/#param-effectCheckScript)

[effectCheckScript for `runNixOps2`](https://github.com/hercules-ci/hercules-ci-effects/blob/2e165352d92782e7ae149f4f1a9b3174f718a3af/effects/nixops2/run-nixops2.nix#L159-L165)

**Comment by roberth** [comment] 2022-01-26 17:12
Ah, sorry. I wrongly assumed `runNixOps2`. This should help you set that attribute for the workaround: https://github.com/hercules-ci/hercules-ci-effects/pull/53

**Comment by roberth** [comment] 2022-01-26 17:19
> I guess it's set by the agent

The NixOps package is taken from the Nixpkgs you pass to `hercules-ci-effects` when initializing it. The docs have [some examples of initializing the `hercules-ci-effects` library](https://docs.hercules-ci.com/hercules-ci-effects/guide/import-or-pin/).

Effects are as close to hermetic as possible, with approximately everything except secrets and the network passed in via Nix.

NixOps 1 is on life support, so it's unlikely that the problem will be fixed there. I'd recommend to switch to `runNixOps2`, which has a number of fixes, despite not being ready for a release for other reasons. It's an ambitious project.

**Closed** 2022-02-03 21:40 UTC
Labels: bug, workaround or fix available
